name: CI
on:
  push:
    branches:
    - main
    - development
  
  pull_request:
    branches:
    - main

jobs:
    test_job:
        runs-on: windows-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          
          - name: setup-msbuild  
            uses: microsoft/setup-msbuild@v2
                     
          - name: Build solution
            run: msbuild 2PZ.sln -target:2PZ,2PZTEST  
          #- name: Check MSBuild version
          -  run:  ./x64/Release/2PZTEST.exe