name: CI
on:
  push:
    branches:
    - main
  
  pull_request:
    branches:
    - main

jobs:
    test_job:
        runs-on: windows-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          
          #- name: Set up MSBuild
          #  uses: microsoft/setup-msbuild@v1
                     
          - name: Build solution
            uses: msbuild 2PZ.sln /p:Configuration=Release

          #- name: Check MSBuild version
          #  run: msbuild -version
      
            