name: CI
on:
  push:
    branches:
    - main
  
  pull_request:
    branches:
    - main

jobs:
    test_job:
        runs-on: windows-latest
        steps:
          - name: Build
            run: env